package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.Button;
class Screen1 extends Form implements HandlesEventDispatching {
  private TableArrangement TableArrangement1;
  private TableArrangement TableArrangement2;
  private HorizontalArrangement HorizontalArrangement1;
  private TableArrangement TableArrangement4;
  private VerticalArrangement VerticalArrangement2;
  private HorizontalArrangement HorizontalArrangement7;
  private Image Image1;
  private HorizontalArrangement HorizontalArrangement13;
  private Label Label1;
  private HorizontalArrangement HorizontalArrangement6;
  private Image Image2;
  private HorizontalArrangement HorizontalArrangement9;
  private Button Button1;
  private HorizontalArrangement HorizontalArrangement5;
  private Image Image3;
  private HorizontalArrangement HorizontalArrangement10;
  private Button Button2;
  private HorizontalArrangement HorizontalArrangement4;
  private Image Image4;
  private HorizontalArrangement HorizontalArrangement11;
  private Button Button3;
  private HorizontalArrangement HorizontalArrangement3;
  private Image Image5;
  private HorizontalArrangement HorizontalArrangement12;
  private Button Button4;
  private HorizontalArrangement HorizontalArrangement2;
  private Image Image6;
  private HorizontalArrangement HorizontalArrangement14;
  private Button Button5;
  private TableArrangement TableArrangement3;
  private Label Label3;
  private TableArrangement TableArrangement6;
  private HorizontalArrangement HorizontalArrangement16;
  private Button Button7;
  private Button Button8;
  private HorizontalArrangement HorizontalArrangement17;
  private Button Button6;
  private HorizontalArrangement HorizontalArrangement18;
  private HorizontalArrangement HorizontalArrangement19;
  private TableArrangement TableArrangement8;
  private TableArrangement TableArrangement9;
  private HorizontalArrangement HorizontalArrangement25;
  private HorizontalArrangement HorizontalArrangement26;
  private HorizontalArrangement HorizontalArrangement27;
  private Button Button9;
  private Button Button10;
  private TableArrangement TableArrangement10;
  private HorizontalArrangement HorizontalArrangement20;
  private HorizontalArrangement HorizontalArrangement24;
  private Label Label8;
  private Label Label10;
  private Label Label6;
  private Label Label13;
  private Label Label11;
  private Label Label12;
  private Label Label14;
  private Label Label15;
  private HorizontalArrangement HorizontalArrangement28;
  private TableArrangement TableArrangement5;
  private Image Image7;
  private Image Image8;
  private Label Label2;
  private Label Label16;
  protected void $define() {
    this.AlignHorizontal(3);
    this.AlignVertical(2);
    this.AppName("iWallet");
    this.BackgroundColor(0xFF3700B3);
    this.Icon("ePera.png");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Height(-1100);
    TableArrangement1.Width(-1100);
    TableArrangement1.Rows(1);
    TableArrangement2 = new TableArrangement(TableArrangement1);
    TableArrangement2.Column(0);
    TableArrangement2.Columns(1);
    TableArrangement2.Height(-1100);
    TableArrangement2.Width(-1060);
    TableArrangement2.Row(0);
    TableArrangement2.Rows(1);
    TableArrangement2.Visible(false);
    HorizontalArrangement1 = new HorizontalArrangement(TableArrangement2);
    HorizontalArrangement1.AlignHorizontal(3);
    HorizontalArrangement1.AlignVertical(2);
    HorizontalArrangement1.BackgroundColor(0xFF6200EE);
    HorizontalArrangement1.Column(0);
    HorizontalArrangement1.Height(-1100);
    HorizontalArrangement1.Width(-1060);
    HorizontalArrangement1.Row(0);
    TableArrangement4 = new TableArrangement(HorizontalArrangement1);
    TableArrangement4.Height(-1100);
    TableArrangement4.Width(-1060);
    TableArrangement4.Rows(7);
    VerticalArrangement2 = new VerticalArrangement(TableArrangement4);
    VerticalArrangement2.BackgroundColor(0x00FFFFFF);
    VerticalArrangement2.Column(1);
    VerticalArrangement2.Height(-1005);
    VerticalArrangement2.Row(0);
    HorizontalArrangement7 = new HorizontalArrangement(TableArrangement4);
    HorizontalArrangement7.AlignVertical(2);
    HorizontalArrangement7.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement7.Column(0);
    HorizontalArrangement7.Height(-1020);
    HorizontalArrangement7.Row(0);
    Image1 = new Image(HorizontalArrangement7);
    Image1.Height(-1012);
    Image1.Width(-1012);
    Image1.Picture("Account%20Logo.png");
    HorizontalArrangement13 = new HorizontalArrangement(HorizontalArrangement7);
    HorizontalArrangement13.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement13.Height(-1001);
    HorizontalArrangement13.Width(-1004);
    Label1 = new Label(HorizontalArrangement7);
    Label1.FontBold(true);
    Label1.FontItalic(true);
    Label1.FontSize(20);
    Label1.Height(-1006);
    Label1.Width(-1035);
    Label1.Text("@User");
    Label1.TextColor(0xFFFFFFFF);
    HorizontalArrangement6 = new HorizontalArrangement(TableArrangement4);
    HorizontalArrangement6.AlignVertical(2);
    HorizontalArrangement6.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement6.Column(0);
    HorizontalArrangement6.Height(-1015);
    HorizontalArrangement6.Row(1);
    Image2 = new Image(HorizontalArrangement6);
    Image2.Height(-1010);
    Image2.Width(-1010);
    Image2.Picture("MyAccount.png");
    HorizontalArrangement9 = new HorizontalArrangement(HorizontalArrangement6);
    HorizontalArrangement9.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement9.Height(-1001);
    HorizontalArrangement9.Width(-1004);
    Button1 = new Button(HorizontalArrangement6);
    Button1.BackgroundColor(0xFF3700B3);
    Button1.Height(-1008);
    Button1.Width(-1035);
    Button1.Text("My Account");
    Button1.TextColor(0xFFFFFFFF);
    HorizontalArrangement5 = new HorizontalArrangement(TableArrangement4);
    HorizontalArrangement5.AlignVertical(2);
    HorizontalArrangement5.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement5.Column(0);
    HorizontalArrangement5.Height(-1015);
    HorizontalArrangement5.Row(2);
    Image3 = new Image(HorizontalArrangement5);
    Image3.Height(-1010);
    Image3.Width(-1010);
    Image3.Picture("Devices.png");
    HorizontalArrangement10 = new HorizontalArrangement(HorizontalArrangement5);
    HorizontalArrangement10.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement10.Height(-1001);
    HorizontalArrangement10.Width(-1004);
    Button2 = new Button(HorizontalArrangement5);
    Button2.BackgroundColor(0xFF3700B3);
    Button2.Height(-1008);
    Button2.Width(-1035);
    Button2.Text("My Devices");
    Button2.TextColor(0xFFFFFFFF);
    HorizontalArrangement4 = new HorizontalArrangement(TableArrangement4);
    HorizontalArrangement4.AlignVertical(2);
    HorizontalArrangement4.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement4.Column(0);
    HorizontalArrangement4.Height(-1015);
    HorizontalArrangement4.Row(3);
    Image4 = new Image(HorizontalArrangement4);
    Image4.Height(-1010);
    Image4.Width(-1010);
    Image4.Picture("Settings.png");
    HorizontalArrangement11 = new HorizontalArrangement(HorizontalArrangement4);
    HorizontalArrangement11.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement11.Height(-1001);
    HorizontalArrangement11.Width(-1004);
    Button3 = new Button(HorizontalArrangement4);
    Button3.BackgroundColor(0xFF3700B3);
    Button3.Height(-1008);
    Button3.Width(-1035);
    Button3.Text("Settings");
    Button3.TextColor(0xFFFFFFFF);
    HorizontalArrangement3 = new HorizontalArrangement(TableArrangement4);
    HorizontalArrangement3.AlignVertical(2);
    HorizontalArrangement3.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement3.Column(0);
    HorizontalArrangement3.Height(-1015);
    HorizontalArrangement3.Row(4);
    Image5 = new Image(HorizontalArrangement3);
    Image5.Height(-1010);
    Image5.Width(-1010);
    Image5.Picture("About.png");
    HorizontalArrangement12 = new HorizontalArrangement(HorizontalArrangement3);
    HorizontalArrangement12.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement12.Height(-1001);
    HorizontalArrangement12.Width(-1004);
    Button4 = new Button(HorizontalArrangement3);
    Button4.BackgroundColor(0xFF3700B3);
    Button4.Height(-1008);
    Button4.Width(-1035);
    Button4.Text("About");
    Button4.TextColor(0xFFFFFFFF);
    HorizontalArrangement2 = new HorizontalArrangement(TableArrangement4);
    HorizontalArrangement2.AlignVertical(2);
    HorizontalArrangement2.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement2.Column(0);
    HorizontalArrangement2.Height(-1015);
    HorizontalArrangement2.Width(-1060);
    HorizontalArrangement2.Row(6);
    Image6 = new Image(HorizontalArrangement2);
    Image6.Height(-1010);
    Image6.Width(-1010);
    Image6.Picture("Logout.png");
    HorizontalArrangement14 = new HorizontalArrangement(HorizontalArrangement2);
    HorizontalArrangement14.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement14.Height(-1001);
    HorizontalArrangement14.Width(-1004);
    Button5 = new Button(HorizontalArrangement2);
    Button5.BackgroundColor(0xFF3700B3);
    Button5.FontSize(16);
    Button5.Height(-1008);
    Button5.Width(-1035);
    Button5.Text("Logout");
    Button5.TextColor(0xFFFFFFFF);
    TableArrangement3 = new TableArrangement(TableArrangement1);
    TableArrangement3.Column(1);
    TableArrangement3.Columns(1);
    TableArrangement3.Height(-1100);
    TableArrangement3.Width(-1100);
    TableArrangement3.Row(0);
    TableArrangement3.Rows(4);
    Label3 = new Label(TableArrangement3);
    Label3.Column(0);
    Label3.FontSize(22);
    Label3.Height(-1006);
    Label3.Width(-1100);
    Label3.Row(1);
    Label3.Text("$ 0.00");
    Label3.TextColor(0xFFFFFFFF);
    TableArrangement6 = new TableArrangement(TableArrangement3);
    TableArrangement6.Column(0);
    TableArrangement6.Columns(5);
    TableArrangement6.Height(-1010);
    TableArrangement6.Row(2);
    TableArrangement6.Rows(1);
    HorizontalArrangement16 = new HorizontalArrangement(TableArrangement6);
    HorizontalArrangement16.AlignHorizontal(3);
    HorizontalArrangement16.AlignVertical(2);
    HorizontalArrangement16.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement16.Column(4);
    HorizontalArrangement16.Height(-1001);
    HorizontalArrangement16.Width(-1012);
    HorizontalArrangement16.Row(0);
    Button7 = new Button(TableArrangement6);
    Button7.BackgroundColor(0xFF6200EE);
    Button7.Column(2);
    Button7.Height(-1007);
    Button7.Width(-1025);
    Button7.Row(0);
    Button7.Text("Receive");
    Button7.TextColor(0xFFFFFFFF);
    Button8 = new Button(TableArrangement6);
    Button8.BackgroundColor(0xFF6200EE);
    Button8.Column(1);
    Button8.Height(-1007);
    Button8.Width(-1025);
    Button8.Row(0);
    Button8.Text("Send");
    Button8.TextColor(0xFFFFFFFF);
    HorizontalArrangement17 = new HorizontalArrangement(TableArrangement6);
    HorizontalArrangement17.AlignHorizontal(3);
    HorizontalArrangement17.AlignVertical(2);
    HorizontalArrangement17.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement17.Column(0);
    HorizontalArrangement17.Height(-1002);
    HorizontalArrangement17.Width(-1013);
    HorizontalArrangement17.Row(0);
    Button6 = new Button(TableArrangement6);
    Button6.BackgroundColor(0xFF6200EE);
    Button6.Column(3);
    Button6.Height(-1007);
    Button6.Width(-1025);
    Button6.Row(0);
    Button6.Text("Add");
    Button6.TextColor(0xFFFFFFFF);
    HorizontalArrangement18 = new HorizontalArrangement(TableArrangement3);
    HorizontalArrangement18.AlignHorizontal(3);
    HorizontalArrangement18.AlignVertical(2);
    HorizontalArrangement18.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement18.Column(0);
    HorizontalArrangement18.Height(-1075);
    HorizontalArrangement18.Width(-1100);
    HorizontalArrangement18.Row(3);
    HorizontalArrangement19 = new HorizontalArrangement(HorizontalArrangement18);
    HorizontalArrangement19.BackgroundColor(0xFFFFFFFF);
    HorizontalArrangement19.Height(-1075);
    HorizontalArrangement19.Width(-1095);
    TableArrangement8 = new TableArrangement(HorizontalArrangement19);
    TableArrangement8.Columns(1);
    TableArrangement8.Height(-1075);
    TableArrangement8.Width(-1095);
    TableArrangement9 = new TableArrangement(TableArrangement8);
    TableArrangement9.Column(0);
    TableArrangement9.Columns(5);
    TableArrangement9.Height(-1010);
    TableArrangement9.Width(-1100);
    TableArrangement9.Row(0);
    TableArrangement9.Rows(1);
    HorizontalArrangement25 = new HorizontalArrangement(TableArrangement9);
    HorizontalArrangement25.Column(0);
    HorizontalArrangement25.Height(-1001);
    HorizontalArrangement25.Width(-1010);
    HorizontalArrangement25.Row(0);
    HorizontalArrangement26 = new HorizontalArrangement(TableArrangement9);
    HorizontalArrangement26.Column(2);
    HorizontalArrangement26.Height(-1001);
    HorizontalArrangement26.Width(-1016);
    HorizontalArrangement26.Row(0);
    HorizontalArrangement27 = new HorizontalArrangement(TableArrangement9);
    HorizontalArrangement27.Column(4);
    HorizontalArrangement27.Height(-1001);
    HorizontalArrangement27.Width(-1010);
    HorizontalArrangement27.Row(0);
    Button9 = new Button(TableArrangement9);
    Button9.BackgroundColor(0xFF3700B3);
    Button9.Column(1);
    Button9.FontSize(18);
    Button9.Height(-1008);
    Button9.Width(-1032);
    Button9.Row(0);
    Button9.Text("Sent");
    Button9.TextColor(0xFFFFFFFF);
    Button10 = new Button(TableArrangement9);
    Button10.BackgroundColor(0xFFFFFFFF);
    Button10.Column(3);
    Button10.FontSize(18);
    Button10.Height(-1008);
    Button10.Width(-1032);
    Button10.Row(0);
    Button10.Text("Received");
    Button10.TextColor(0xFF3700B3);
    TableArrangement10 = new TableArrangement(TableArrangement8);
    TableArrangement10.Column(0);
    TableArrangement10.Columns(5);
    TableArrangement10.Height(-1070);
    TableArrangement10.Width(-1020);
    TableArrangement10.Row(1);
    TableArrangement10.Rows(7);
    HorizontalArrangement20 = new HorizontalArrangement(TableArrangement10);
    HorizontalArrangement20.AlignHorizontal(3);
    HorizontalArrangement20.AlignVertical(2);
    HorizontalArrangement20.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement20.Column(0);
    HorizontalArrangement20.Height(-1001);
    HorizontalArrangement20.Width(-1015);
    HorizontalArrangement20.Row(2);
    HorizontalArrangement24 = new HorizontalArrangement(TableArrangement10);
    HorizontalArrangement24.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement24.Column(2);
    HorizontalArrangement24.Height(-1001);
    HorizontalArrangement24.Width(-1020);
    HorizontalArrangement24.Row(2);
    Label8 = new Label(TableArrangement10);
    Label8.Column(1);
    Label8.FontSize(16);
    Label8.Width(-1020);
    Label8.Row(0);
    Label8.Text("Date");
    Label10 = new Label(TableArrangement10);
    Label10.Column(1);
    Label10.FontSize(15);
    Label10.Height(-1004);
    Label10.Width(-1020);
    Label10.Row(1);
    Label10.Text("1-2-2021");
    Label10.TextColor(0xFF888888);
    Label6 = new Label(TableArrangement10);
    Label6.Column(3);
    Label6.FontSize(16);
    Label6.Width(-1020);
    Label6.Row(0);
    Label6.Text("Amount");
    Label13 = new Label(TableArrangement10);
    Label13.Column(3);
    Label13.FontSize(15);
    Label13.Height(-1004);
    Label13.Width(-1020);
    Label13.Row(1);
    Label13.Text("$500");
    Label13.TextColor(0xFF888888);
    Label11 = new Label(TableArrangement10);
    Label11.Column(1);
    Label11.FontSize(15);
    Label11.Height(-1004);
    Label11.Width(-1020);
    Label11.Row(2);
    Label11.Text("1-2-2021");
    Label11.TextColor(0xFF888888);
    Label12 = new Label(TableArrangement10);
    Label12.Column(1);
    Label12.FontSize(15);
    Label12.Height(-1004);
    Label12.Width(-1020);
    Label12.Row(3);
    Label12.Text("1-2-2021");
    Label12.TextColor(0xFF888888);
    Label14 = new Label(TableArrangement10);
    Label14.Column(3);
    Label14.FontSize(15);
    Label14.Height(-1004);
    Label14.Width(-1020);
    Label14.Row(2);
    Label14.Text("$500");
    Label14.TextColor(0xFF888888);
    Label15 = new Label(TableArrangement10);
    Label15.Column(3);
    Label15.FontSize(15);
    Label15.Height(-1004);
    Label15.Width(-1020);
    Label15.Row(3);
    Label15.Text("$500");
    Label15.TextColor(0xFF888888);
    HorizontalArrangement28 = new HorizontalArrangement(TableArrangement10);
    HorizontalArrangement28.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement28.Column(4);
    HorizontalArrangement28.Height(-1002);
    HorizontalArrangement28.Width(-1015);
    HorizontalArrangement28.Row(2);
    TableArrangement5 = new TableArrangement(TableArrangement3);
    TableArrangement5.Column(0);
    TableArrangement5.Columns(3);
    TableArrangement5.Height(-1020);
    TableArrangement5.Width(-1100);
    TableArrangement5.Row(0);
    Image7 = new Image(TableArrangement5);
    Image7.Column(0);
    Image7.Height(-1015);
    Image7.Width(-1015);
    Image7.Picture("MenuToggleButton.png");
    Image7.Row(0);
    Image8 = new Image(TableArrangement5);
    Image8.Column(2);
    Image8.Height(-1015);
    Image8.Width(-1015);
    Image8.Picture("MyAccount.png");
    Image8.Row(0);
    Label2 = new Label(TableArrangement5);
    Label2.Column(1);
    Label2.Height(-1004);
    Label2.Width(-1070);
    Label2.Row(1);
    Label2.Text("@User");
    Label2.TextColor(0xFFCCCCCC);
    Label16 = new Label(TableArrangement5);
    Label16.Column(1);
    Label16.FontSize(25);
    Label16.Height(-1010);
    Label16.Row(0);
    Label16.Text("ePera");
    Label16.TextColor(0xFFFFFFFF);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}